version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: src/infra/docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../.env
    depends_on:
      - temporal
    
  temporal:
    image: temporalio/auto-setup:1.19.1
    ports:
      - "7233:7233"
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
    
  temporal-ui:
    image: temporalio/ui:2.10.0
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
